# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4V9vkA93XIPC6J6BWlYUpMiZqmC82ns
"""

!pip -q install --upgrade gradio

import gradio as gr
import json
import os
from datetime import date

DATA_FILE = "english_student_data.json"

student = {
    "name": "",
    "level": "Beginner",
    "time": "15 minutes",
    "completed": 0,
    "quiz_scores": [],
    "vocabulary": [],
    "mistakes": [],
    "streak": 1
}

if os.path.exists(DATA_FILE):
    try:
        with open(DATA_FILE, "r") as f:
            student.update(json.load(f))
    except:
        pass


def save_data():
    with open(DATA_FILE, "w") as f:
        json.dump(student, f, indent=2)


lessons = [
    {
        "title": "Greetings",
        "topic": "Vocabulary",
        "content": """
# Lesson 1: Greetings

Learn these common English greetings:

- Hello = a greeting
- Hi = an informal greeting
- Good morning = greeting used in the morning
- Good evening = greeting used in the evening
- Goodbye = used when leaving

### Examples

**Hello! How are you?**

**Hi! My name is Ali.**

**Good morning, teacher.**
"""
    },
    {
        "title": "Pronouns",
        "topic": "Grammar",
        "content": """
# Lesson 2: Pronouns

Pronouns are words we use instead of names.

- I
- You
- He
- She
- It
- We
- They

### Examples

**I am a student.**

**She is my sister.**

**They are friends.**
"""
    },
    {
        "title": "Simple Sentences",
        "topic": "Sentence Building",
        "content": """
# Lesson 3: Simple Sentences

A simple English sentence usually has:

**Subject + Verb + Object**

### Examples

I eat food.

She reads a book.

They play football.

### Remember

Start a sentence with a capital letter and finish it with punctuation.
"""
    },
    {
        "title": "Present Simple",
        "topic": "Grammar",
        "content": """
# Lesson 4: Present Simple

We use the present simple for habits and things that happen regularly.

### Examples

I go to school.

You play football.

She goes to school.

He likes tea.

Remember: with **he / she / it**, the verb often gets **s** or **es**.
"""
    }
]

current_lesson = {"index": 0}

def create_profile(name, level, time):
    if not name.strip():
        return "⚠️ Please enter your name."

    student["name"] = name.strip()
    student["level"] = level
    student["time"] = time

    save_data()

    return f"""
## Welcome, {student["name"]}! 👋

Your profile has been created.

**Level:** {student["level"]}
**Daily study time:** {student["time"]}

Your personalized English learning journey is ready!
"""


profile_output = gr.Markdown()

profile_demo = gr.Interface(
    fn=create_profile,
    inputs=[
        gr.Textbox(label="Your Name", placeholder="Enter your name"),
        gr.Dropdown(
            ["Beginner", "Elementary"],
            value="Beginner",
            label="English Level"
        ),
        gr.Radio(
            ["15 minutes", "30 minutes", "45 minutes", "60 minutes"],
            value="15 minutes",
            label="Daily Learning Time"
        )
    ],
    outputs=profile_output,
    title="👤 Student Profile"
)

profile_demo.launch()

import gradio as gr
import json
import os

DATA_FILE = "english_student_data.json"

student = {
    "name": "",
    "level": "Beginner",
    "time": "15 minutes",
    "completed": 0,
    "quiz_scores": [],
    "vocabulary": [],
    "mistakes": [],
    "streak": 1
}

if os.path.exists(DATA_FILE):
    try:
        with open(DATA_FILE, "r") as f:
            student.update(json.load(f))
    except:
        pass


def save_data():
    with open(DATA_FILE, "w") as f:
        json.dump(student, f, indent=2)


lessons = [
    {
        "title": "Greetings",
        "topic": "Vocabulary",
        "content": """
# 👋 Lesson 1: Greetings

### New Words

**Hello** — a greeting
**Hi** — an informal greeting
**Good morning** — used in the morning
**Good evening** — used in the evening
**Goodbye** — used when leaving

### Examples

Hello! How are you?

Hi! My name is Sara.

Good morning, teacher.
"""
    },
    {
        "title": "Pronouns",
        "topic": "Grammar",
        "content": """
# 📚 Lesson 2: Pronouns

Pronouns are words we use instead of names.

**I • You • He • She • It • We • They**

### Examples

I am a student.

She is my sister.

They are friends.
"""
    },
    {
        "title": "Simple Sentences",
        "topic": "Sentence Building",
        "content": """
# ✏️ Lesson 3: Simple Sentences

A simple sentence can follow:

**Subject + Verb + Object**

Examples:

I eat food.

She reads a book.

They play football.

Remember to start with a capital letter.
"""
    },
    {
        "title": "Present Simple",
        "topic": "Grammar",
        "content": """
# 📖 Lesson 4: Present Simple

We use the present simple for habits and regular actions.

Examples:

I go to school.

You play football.

She goes to school.

He likes tea.

### Remember

With **he / she / it**, we often add **s** or **es**.
"""
    }
]


def profile(name, level, time):
    if not name.strip():
        return "⚠️ Please enter your name first."

    student["name"] = name.strip()
    student["level"] = level
    student["time"] = time

    save_data()

    return f"""
## Welcome, {student["name"]}! 👋

**Level:** {level}
**Daily time:** {time}

Your learning plan is ready. Start today's lesson!
"""


def dashboard():
    total = len(lessons)
    completed = min(student["completed"], total)

    progress = int((completed / total) * 100)

    recommended = lessons[completed]["title"] if completed < total else "Revision"

    return f"""
# 🏠 Welcome {student["name"] or "Student"}!

### Today's Learning
**Recommended lesson:** {recommended}

### Your Progress
**{progress}%**

Lessons completed: **{completed}/{total}**

Learning streak: 🔥 **{student["streak"]} day**

Daily study time: **{student["time"]}**

### Recommended Practice
Practice your vocabulary and review your recent mistakes.
"""


def start_lesson():
    index = min(student["completed"], len(lessons) - 1)

    lesson = lessons[index]

    return f"""
{lesson["content"]}

---

### 🎯 Your Task

Read the lesson carefully, then go to **Practice** and test yourself.
"""


def complete_lesson():
    if student["completed"] < len(lessons):
        student["completed"] += 1
        save_data()

    return dashboard()


def check_quiz(answer):
    correct = answer == "goes"

    if correct:
        student["quiz_scores"].append(1)
        message = "✅ Correct! Great job!"
    else:
        student["quiz_scores"].append(0)

        if "goes" not in student["mistakes"]:
            student["mistakes"].append("Present simple: he/she/it")

        message = """
❌ Not quite.

The correct answer is **goes**.

We say:

**She goes to school.**

With **she**, we use **goes**.
"""

    save_data()
    return message


def check_reading(answer):
    if answer.lower().strip() == "ali":
        return "✅ Correct! Ali is the student in the passage."
    return "❌ Try again. Read the passage once more."


def check_writing(text):
    if not text.strip():
        return "Please write a sentence first."

    text_lower = text.lower().strip()

    if "she go" in text_lower:
        if "she goes" not in text_lower:
            student["mistakes"].append("She + goes")
            save_data()

            return """
### Almost correct! 👍

You wrote:

**She go...**

Use **goes** with "she".

✅ Correct:

**She goes to school.**
"""

    return """
### Good effort! 🌟

Your sentence has been received.

Keep practicing English every day!
"""


def ask_ai(question):
    if not question.strip():
        return "Please ask me an English question."

    q = question.lower()

    if "hello" in q or "hi" in q:
        return """
👋 Hello!

You can ask me things like:

- What does "happy" mean?
- Explain present tense.
- Correct my sentence.
- Give me 5 English sentences.
"""

    if "present" in q:
        return """
### Present Simple

We use the present simple for habits and regular actions.

Examples:

**I play football.**

**She plays football.**

Remember: with **he, she, it**, we usually add **s** or **es**.
"""

    if "correct" in q or "sentence" in q:
        return """
Sure! 😊

Write your English sentence and I will help you correct it.

Example:

❌ She go to school.

✅ She goes to school.
"""

    if "word" in q or "meaning" in q:
        return """
Tell me the English word you want to understand.

I can give you:

- Simple meaning
- Example sentence
- Easy explanation
"""

    return f"""
🤖 **English Teacher**

You asked:

> {question}

For this beginner version, I can help with basic vocabulary, grammar, sentences, reading and writing.

Try asking:

**"Explain present simple."**
"""


def progress():
    total = len(lessons)
    completed = min(student["completed"], total)
    percent = int((completed / total) * 100)

    scores = student["quiz_scores"]

    if scores:
        quiz_percent = int((sum(scores) / len(scores)) * 100)
    else:
        quiz_percent = 0

    mistakes = ", ".join(student["mistakes"]) if student["mistakes"] else "None yet"

    return f"""
# 📊 Your Progress

### Overall Progress
**{percent}%**

### Lessons
**{completed}/{total} completed**

### Quiz Score
**{quiz_percent}%**

### Vocabulary
**{len(student["vocabulary"])} words**

### Learning Streak
🔥 **{student["streak"]} days**

### Common Mistakes
{mistakes}

Keep practicing! 🌟
"""


with gr.Blocks(
    title="English Learning App",
    theme=gr.themes.Soft()
) as app:

    gr.Markdown("""
# 🌟 English Learning App

### Learn English step by step — simple, short and friendly.
""")

    with gr.Tab("👤 Profile"):
        name = gr.Textbox(label="Your Name")
        level = gr.Dropdown(
            ["Beginner", "Elementary"],
            value="Beginner",
            label="English Level"
        )
        time = gr.Radio(
            ["15 minutes", "30 minutes", "45 minutes", "60 minutes"],
            value="15 minutes",
            label="Daily Learning Time"
        )

        profile_btn = gr.Button("Create / Update Profile", variant="primary")
        profile_result = gr.Markdown()

        profile_btn.click(
            profile,
            inputs=[name, level, time],
            outputs=profile_result
        )

    with gr.Tab("🏠 Home"):
        dashboard_output = gr.Markdown()
        refresh_btn = gr.Button("Refresh Dashboard")

        refresh_btn.click(
            dashboard,
            outputs=dashboard_output
        )

    with gr.Tab("📚 Learn"):
        lesson_output = gr.Markdown()

        start_btn = gr.Button(
            "▶️ Start Today's Lesson",
            variant="primary"
        )

        complete_btn = gr.Button("✅ Complete Lesson")

        start_btn.click(
            start_lesson,
            outputs=lesson_output
        )

        complete_btn.click(
            complete_lesson,
            outputs=dashboard_output
        )

    with gr.Tab("🎯 Practice"):
        gr.Markdown("""
# Quick Practice

Complete the sentence:

### She ___ to school every day.
""")

        quiz_answer = gr.Radio(
            ["go", "goes", "going", "gone"],
            label="Choose the correct answer"
        )

        quiz_btn = gr.Button("Check Answer", variant="primary")
        quiz_result = gr.Markdown()

        quiz_btn.click(
            check_quiz,
            inputs=quiz_answer,
            outputs=quiz_result
        )

    with gr.Tab("📖 Reading"):
        gr.Markdown("""
# 📖 Reading Practice

### Read the passage:

**Ali is a student. He lives in Lahore.
He goes to school every morning.
He likes English.**

### Question:

What is the student's name?
""")

        reading_answer = gr.Textbox(label="Your Answer")
        reading_btn = gr.Button("Check Answer")
        reading_result = gr.Markdown()

        reading_btn.click(
            check_reading,
            inputs=reading_answer,
            outputs=reading_result
        )

    with gr.Tab("✍️ Writing"):
        gr.Markdown("""
# ✍️ Writing Practice

Write one simple English sentence.

Example:

**I like apples.**
""")

        writing_input = gr.Textbox(
            label="Write your sentence",
            lines=3
        )

        writing_btn = gr.Button(
            "Check My Writing",
            variant="primary"
        )

        writing_result = gr.Markdown()

        writing_btn.click(
            check_writing,
            inputs=writing_input,
            outputs=writing_result
        )

    with gr.Tab("🤖 Ask AI"):
        gr.Markdown("""
# 🤖 AI English Assistant

Ask your English teacher anything.

Examples:

- What does "beautiful" mean?
- Explain present tense.
- Correct my sentence.
- Give me 5 English sentences.
""")

        ai_question = gr.Textbox(
            label="Ask your question",
            lines=3
        )

        ai_btn = gr.Button(
            "Ask AI",
            variant="primary"
        )

        ai_result = gr.Markdown()

        ai_btn.click(
            ask_ai,
            inputs=ai_question,
            outputs=ai_result
        )

    with gr.Tab("📊 Progress"):
        progress_output = gr.Markdown()

        progress_btn = gr.Button("Refresh Progress")

        progress_btn.click(
            progress,
            outputs=progress_output
        )


app.launch(share=True)